
# ...
name: Trivy Scan of Github repo
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: Ubuntu-24.04
    steps:
      - name: Create Output Directory
        run: mkdir -P "GitHub Actions/Trivy_Automation"

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.60.0
        
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@0.28.0
        with:
          version: v0.28.0
          cache: true

      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Run Trivy vuln scanner in Github repo
        uses: aquasecurity/trivy-action@main
        with:
          scan-type: 'repo'
          ignore-unfixed: true
          format: 'sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy_scan_results.sarif'
    
 
