
# ...
name: Trivy Scan of Github repo
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: Ubuntu-24.04
    steps:
      - name: Create Output Directory
        run: mkdir -P "GitHub Actions/Trivy_Automation"

      - name: Install Aqua Security Trivy install
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.28.0
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Run Trivy vuln scanner in Github repo
        uses: aquasecurity/trivy-action@v0.2.2
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy_scan_results.sarif'
    
 
